# Generated by Django 6.0.1 on 2026-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.AddField(
            model_name='course',
            name='colleges',
            field=models.ManyToManyField(related_name='courses', to='accounts.college'),
        ),
    ]
