# Generated by Django 6.0.1 on 2026-04-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='domain',
        ),
    ]
