# Generated by Django 6.0.1 on 2026-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_mentor_course_remove_mentor_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
