# Generated by Django 6.0.1 on 2026-04-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_application_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
    ]
