# Generated by Django 6.0.1 on 2026-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_application_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
